# © VampSecure Studios — VampSecure Labs Security Research Division
"""
vamp_llm_probe — LLM Security Auditor.

Exporta todos los símbolos públicos del paquete para mantener compatibilidad
con el módulo plano anterior (`import vamp_llm_probe as llm_probe`).
"""
from ._models import (
    VERSION,
    TOOL_NAME,
    TOOL,
    FINDING_PREFIX,
    COPYRIGHT,
    MODEL_SPECIFIC_PACKS,
    C,
    EstadoEndpoint,
    log_info,
    log_ok,
    log_warn,
    log_err,
    log_verbose,
    log_hallazgo,
    cabecera_fase,
    resumen_hallazgos,
    _set_verbose,
    _REFUSAL_PATTERNS,
    _COMPLIANCE_MARKERS,
    _UNICODE_TAGS_INICIO,
    _UNICODE_TAGS_FIN,
    _FLAGS_LEGITIMOS,
    _ASCII_EXEC_MARKERS,
    PAYLOADS_INYECCION,
    _INYECCION_BUNDLED_ES,
    _JAILBREAK_BUNDLED_ES,
    _RAG_INJECTION_PAYLOADS,
    _RAG_EXTRACTION_PAYLOADS,
    _RAG_BYPASS_MARKERS,
    _RAG_LEAK_MARKERS,
    _RAG_DOC_INJECTION_PAYLOADS,
    _RAG_EXEC_MARKERS,
    _MODEL_META_PAYLOADS,
    _META_LEAK_MARKERS,
    _CADENAS_MULTITURN,
    Finding,
    ReportMeta,
    VampSecReport,
)
from ._core import (
    construir_peticion,
    extraer_texto_respuesta,
    fase_reconocimiento,
    _detectar_formato_y_modelos,
    _comprobar_acceso_sin_auth,
    _comprobar_version_expuesta,
    _detectar_ascii_smuggling,
    _detectar_injection_exitosa,
    _dir_payloads,
    _descargar_payloads,
    _cargar_dataset_jailbreaks,
    _cargar_dataset_injection,
    _cargar_dataset_forbidden,
    _cargar_dataset_injection_es,
    _cargar_dataset_jailbreaks_es,
    _generar_payloads_ascii_smuggling,
    _detectar_injection_exitosa_ds,
    _detectar_jailbreak_exitoso_ds,
    _detectar_respuesta_prohibida,
    fase_inyeccion,
    fase_evasion,
    fase_extraccion,
    fase_controles,
    _enviar_inferencia,
    _calcular_diferencia,
    _detectar_contenido_sensible,
    _etiquetas_owasp,
    _aplicar_tags_owasp,
    LLMProbe,
    fase_dataset,
    _detectar_familia_modelo,
    fase_model_specific_packs,
    fase_rag_poisoning,
    fase_multiturn,
)
from .cli import construir_parser, main_async, main, BANNER

__all__ = [
    # versión
    "VERSION",
    # modelos / constantes
    "TOOL_NAME", "TOOL", "FINDING_PREFIX", "COPYRIGHT", "BANNER",
    "MODEL_SPECIFIC_PACKS",
    "C", "EstadoEndpoint",
    # logging
    "log_info", "log_ok", "log_warn", "log_err", "log_verbose",
    "log_hallazgo", "cabecera_fase", "resumen_hallazgos", "_set_verbose",
    # detección
    "_REFUSAL_PATTERNS", "_COMPLIANCE_MARKERS",
    "_UNICODE_TAGS_INICIO", "_UNICODE_TAGS_FIN",
    "_FLAGS_LEGITIMOS", "_ASCII_EXEC_MARKERS",
    # payloads
    "PAYLOADS_INYECCION", "_INYECCION_BUNDLED_ES", "_JAILBREAK_BUNDLED_ES",
    "_RAG_INJECTION_PAYLOADS", "_RAG_EXTRACTION_PAYLOADS",
    "_RAG_BYPASS_MARKERS", "_RAG_LEAK_MARKERS",
    "_RAG_DOC_INJECTION_PAYLOADS", "_RAG_EXEC_MARKERS",
    "_MODEL_META_PAYLOADS", "_META_LEAK_MARKERS", "_CADENAS_MULTITURN",
    # report
    "Finding", "ReportMeta", "VampSecReport",
    # core
    "construir_peticion", "extraer_texto_respuesta",
    "fase_reconocimiento",
    "_detectar_formato_y_modelos", "_comprobar_acceso_sin_auth",
    "_comprobar_version_expuesta",
    "_detectar_ascii_smuggling", "_detectar_injection_exitosa",
    "_dir_payloads", "_descargar_payloads",
    "_cargar_dataset_jailbreaks", "_cargar_dataset_injection",
    "_cargar_dataset_forbidden",
    "_cargar_dataset_injection_es", "_cargar_dataset_jailbreaks_es",
    "_generar_payloads_ascii_smuggling",
    "_detectar_injection_exitosa_ds", "_detectar_jailbreak_exitoso_ds",
    "_detectar_respuesta_prohibida",
    "fase_inyeccion", "fase_evasion", "fase_extraccion", "fase_controles",
    "_enviar_inferencia", "_calcular_diferencia", "_detectar_contenido_sensible",
    "_etiquetas_owasp", "_aplicar_tags_owasp",
    "LLMProbe", "fase_dataset",
    "_detectar_familia_modelo", "fase_model_specific_packs",
    "fase_rag_poisoning", "fase_multiturn",
    # cli
    "construir_parser", "main_async", "main",
]
